[build]
  functions = "functions/"
  publish = "dist/"
  command = "export ELM_HOME=\"$NETLIFY_BUILD_BASE/cache/elm\" && npm install && make build"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200

[dev]
  command = "npm start"
  targetPort = 1234
  autoLaunch = true
  framework = "#custom"

[functions]
  node_bundler = "esbuild"
